version: "3.8"

volumes:
  cowrie-etc:
  cowrie-var:
  cowrie-src:
  elasticsearch-data:

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie-cowrie
    restart: always
    ports:
      - "22:2222"
      - "23:2223"
    volumes:
      - cowrie-var:/cowrie/cowrie-git/var
      - cowrie-src:/cowrie/cowrie-git/src
      - ./cowrie-config/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      - ./cowrie-config/motd:/cowrie/cowrie-git/honeyfs/etc/motd

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: cowrie-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - stack

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: cowrie-logstash
    restart: always
    volumes:
      - ./elastic-config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./GeoLite2-City.mmdb:/opt/logstash/vendor/geoip/GeoLite2-City.mmdb
    depends_on:
      - elasticsearch
    networks:
      - stack

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.1
    container_name: cowrie-filebeat
    restart: always
    command: ["--strict.perms=false"]
    volumes:
      - ./elastic-config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - cowrie-var:/cowrie/cowrie-git/var
    depends_on:
      - logstash
    networks:
      - stack

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: cowrie-kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    entrypoint:
      - sh
      - -c
      - |
        export KIBANA_BASIC_AUTH=admin:$(htpasswd -nbB admin "$KIBANA_PASSWORD" | cut -d':' -f2)
        echo "Ustawiono KIBANA_BASIC_AUTH=$KIBANA_BASIC_AUTH"
        exec /usr/local/bin/kibana-docker
    networks:
      - stack
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana.meetgine.com`)"
      - "traefik.http.routers.kibana.entrypoints=websecure"
      - "traefik.http.routers.kibana.tls=true"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"

networks:
  stack:
    internal: true
  dokploy-network:
    external: true
